name: Development Distribution For develop

on:
  push:
    branches:
      - develop

jobs:
  dev-distribution:
    runs-on: ubuntu-latest
    name: Development Distribution
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v4
      with: 
         node-version: 18
  

    - name: Install node modules
      run: npm i --force

    - name: Run test
      run: npm run action-test

    - name: init Gradel
      uses: gradle/actions/setup-gradle@v3

    - name: Cache Gradle Wrapper
      uses: actions/cache@v2
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

    - name: Cache Gradle Dependencies
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-caches-

    # - name: Make Gradlew Executable
    #   run: cd android && chmod +x ./gradlew

    - name: Build Android Release
      run: |
           ./gradlew build 

    # - name: Upload Artifact
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: app-release.apk
    #     path: android/app/build/outputs/apk/release/

